// Generated by gencpp from file myquad/F64.msg
// DO NOT EDIT!


#ifndef MYQUAD_MESSAGE_F64_H
#define MYQUAD_MESSAGE_F64_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myquad
{
template <class ContainerAllocator>
struct F64_
{
  typedef F64_<ContainerAllocator> Type;

  F64_()
    : angle(0.0)  {
    }
  F64_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::myquad::F64_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myquad::F64_<ContainerAllocator> const> ConstPtr;

}; // struct F64_

typedef ::myquad::F64_<std::allocator<void> > F64;

typedef boost::shared_ptr< ::myquad::F64 > F64Ptr;
typedef boost::shared_ptr< ::myquad::F64 const> F64ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myquad::F64_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myquad::F64_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::myquad::F64_<ContainerAllocator1> & lhs, const ::myquad::F64_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::myquad::F64_<ContainerAllocator1> & lhs, const ::myquad::F64_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace myquad

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::myquad::F64_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myquad::F64_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myquad::F64_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myquad::F64_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myquad::F64_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myquad::F64_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myquad::F64_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4edb55038e2b888976a0c0c56935341c";
  }

  static const char* value(const ::myquad::F64_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4edb55038e2b8889ULL;
  static const uint64_t static_value2 = 0x76a0c0c56935341cULL;
};

template<class ContainerAllocator>
struct DataType< ::myquad::F64_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myquad/F64";
  }

  static const char* value(const ::myquad::F64_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myquad::F64_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n"
;
  }

  static const char* value(const ::myquad::F64_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myquad::F64_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct F64_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myquad::F64_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myquad::F64_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYQUAD_MESSAGE_F64_H
