// Generated by gencpp from file myquad/Ins.msg
// DO NOT EDIT!


#ifndef MYQUAD_MESSAGE_INS_H
#define MYQUAD_MESSAGE_INS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace myquad
{
template <class ContainerAllocator>
struct Ins_
{
  typedef Ins_<ContainerAllocator> Type;

  Ins_()
    : header()
    , arr()  {
    }
  Ins_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , arr(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _arr_type;
  _arr_type arr;





  typedef boost::shared_ptr< ::myquad::Ins_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myquad::Ins_<ContainerAllocator> const> ConstPtr;

}; // struct Ins_

typedef ::myquad::Ins_<std::allocator<void> > Ins;

typedef boost::shared_ptr< ::myquad::Ins > InsPtr;
typedef boost::shared_ptr< ::myquad::Ins const> InsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myquad::Ins_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myquad::Ins_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::myquad::Ins_<ContainerAllocator1> & lhs, const ::myquad::Ins_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.arr == rhs.arr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::myquad::Ins_<ContainerAllocator1> & lhs, const ::myquad::Ins_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace myquad

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::myquad::Ins_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myquad::Ins_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myquad::Ins_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myquad::Ins_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myquad::Ins_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myquad::Ins_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myquad::Ins_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51824bbaac648d885c19de11971ce20b";
  }

  static const char* value(const ::myquad::Ins_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51824bbaac648d88ULL;
  static const uint64_t static_value2 = 0x5c19de11971ce20bULL;
};

template<class ContainerAllocator>
struct DataType< ::myquad::Ins_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myquad/Ins";
  }

  static const char* value(const ::myquad::Ins_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myquad::Ins_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] arr\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::myquad::Ins_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myquad::Ins_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.arr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ins_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myquad::Ins_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myquad::Ins_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "arr[]" << std::endl;
    for (size_t i = 0; i < v.arr.size(); ++i)
    {
      s << indent << "  arr[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.arr[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYQUAD_MESSAGE_INS_H
