// Generated by gencpp from file myquad/mysrv.msg
// DO NOT EDIT!


#ifndef MYQUAD_MESSAGE_MYSRV_H
#define MYQUAD_MESSAGE_MYSRV_H

#include <ros/service_traits.h>


#include <myquad/mysrvRequest.h>
#include <myquad/mysrvResponse.h>


namespace myquad
{

struct mysrv
{

typedef mysrvRequest Request;
typedef mysrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mysrv
} // namespace myquad


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myquad::mysrv > {
  static const char* value()
  {
    return "043c37660891c202c07ae9cb667631f0";
  }

  static const char* value(const ::myquad::mysrv&) { return value(); }
};

template<>
struct DataType< ::myquad::mysrv > {
  static const char* value()
  {
    return "myquad/mysrv";
  }

  static const char* value(const ::myquad::mysrv&) { return value(); }
};


// service_traits::MD5Sum< ::myquad::mysrvRequest> should match
// service_traits::MD5Sum< ::myquad::mysrv >
template<>
struct MD5Sum< ::myquad::mysrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myquad::mysrv >::value();
  }
  static const char* value(const ::myquad::mysrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myquad::mysrvRequest> should match
// service_traits::DataType< ::myquad::mysrv >
template<>
struct DataType< ::myquad::mysrvRequest>
{
  static const char* value()
  {
    return DataType< ::myquad::mysrv >::value();
  }
  static const char* value(const ::myquad::mysrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myquad::mysrvResponse> should match
// service_traits::MD5Sum< ::myquad::mysrv >
template<>
struct MD5Sum< ::myquad::mysrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myquad::mysrv >::value();
  }
  static const char* value(const ::myquad::mysrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myquad::mysrvResponse> should match
// service_traits::DataType< ::myquad::mysrv >
template<>
struct DataType< ::myquad::mysrvResponse>
{
  static const char* value()
  {
    return DataType< ::myquad::mysrv >::value();
  }
  static const char* value(const ::myquad::mysrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYQUAD_MESSAGE_MYSRV_H
